- name: Setup AAP Components
  hosts: localhost
  gather_facts: false
  # vars:
  #   - controller_validate_certs: false

  tasks:
    - name: Setup Components
      ansible.builtin.include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      vars:
        controller_components:
          - credential_types
          - job_templates

          controller_credential_types:
            - name: Red Hat API Credential
              description: Red Hat API Credential
              inputs:
                fields:
                - secret: true
                  type: string
                  id: offline_token
                  label: Offline Token
                required:
                - offline_token
              injectors:
                env:
                  REDHAT_API_OFFLINE_TOKEN: !unsafe "{{ offline_token }}"

          controller_templates:
            - name: "RHEL Lifecycle - Bootstrap"
              job_type: run
              inventory: "Workshop Inventory"
              project: "RHEL Lifecyce Management"
              playbook: "playbooks/satellite.yml"
              execution_environment: Default execution environment
