---
- name: Setup AAP Components
  hosts: localhost
  gather_facts: false
  # vars:
  #   - controller_validate_certs: false

  tasks:
    - name: Setup Components
      ansible.builtin.include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      vars:
        project_name: RHEL Lifecycle Management
        inventory_name: Demo Inventory
        playbook_path: playbooks
        ee_name: RHEL Lifecycle EE

        controller_components:
          - credential_types
          - job_templates

        controller_credential_types:
          - name: Red Hat API Credential
            description: Red Hat API Credential
            inputs:
              fields:
                - secret: true
                  type: string
                  id: offline_token
                  label: Offline Token
              required:
                - offline_token
            injectors:
              env:
                REDHAT_API_OFFLINE_TOKEN: !unsafe "{{ offline_token }}"

        controller_templates:
          - name: "RHEL Lifecycle - Bootstrap"
            job_type: run
            inventory: "{{ inventory_name }}"
            project: "{{ project_name }}"
            playbook: "{{ playbook_path }}/satellite.yml"
            execution_environment: "{{ ee_name }}"
