---
- name: Setup Red Hat Subscription Allocation
  hosts: localhost
  gather_facts: false
  vars:
        redhat_api_offline_token: "{{ lookup('ansible.builtin.env', 'REDHAT_API_OFFLINE_TOKEN') }}"

  tasks:
    - name: Get Red Hat API bearer token
      ansible.builtin.uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ redhat_api_offline_token }}"
        body_format: form-urlencoded
      register: token_request

    - debug:
        var: token_request